### ISSUE TITLE
Articles page tagline

### ISSUE THREAD

**Issue by benjeffery** [wtchg-kwiatkowski/observatory-web#322]
Edited from wordpress settings->general

**Comment by georgebusby** [comment]
I think simpler the better, so will just keep it as "Articles"

**Comment by leehart** [comment]
I think the tagline was the "test" line underneath the "Articles" title.

Personally I think it would be more consistent to not even have the "Articles" title. (Since it says "Articles" in the breadcrumb, and other pages don't have such a bold main title.) Alternatively, I would consistently give all the pages a main title, e.g. "Analysis" as a title on the Analysis page. I think I personally prefer no title, but I can see a benefit to having titles on all the pages where the page is about one thing.
(The home page contains at least three things, and "Home" would look a bit silly as a title, imo. I still like the three big icons idea from the mockups though...)

**Comment by georgebusby** [comment]
yes, I contemplated putting nothing there. But then I thought that the tick boxes looked a little odd on their own up there. but actually, i agree with you that nothing is probably cleaner

**Comment by georgebusby** [comment]
have removed completely

**Comment by leehart** [comment]
I reckon we can remove that surplus white/grey space too, by editing the (`<Feed>`?) component.
