### ISSUE TITLE
Blog editing in WYSIWYG removes panoptes components.

### ISSUE THREAD

**Issue by benjeffery** [wtchg-kwiatkowski/observatory-web#364]
It shouldn't!

**Comment by leehart** [comment]
We're able to use the [`Advanced TinyMCE Configuration` plugin](https://wordpress.org/plugins/advanced-tinymce-configuration/) to specify the `extended_valid_elements` for TinyMCE, but the current snag is case-sensitivity, e.g. we can specify that `FOO` is a valid element, but it gets converted to `foo`, which is either valid or invalid, depending on whether it's also been specified as a valid element, but doesn't help us because we need case-sensitivity, e.g. `DocTemplate` instead of `doctemplate`.
So I'm now looking for a way to prevent the editor from automatically lower-casing elements.

**Comment by leehart** [comment]
Unfortunately, configuring TinyMCE to not lowercase custom elements does not look straightforward.
Potential paths forward include:
1) Developing TinyMCE to not lowercase custom elements. (It looks like the main maintainer of TinyMCE `spocke` has shown some resistance to similar issues in the past, because modern-day HTML elements are invariably lowercase, but it might be worth a try, even if a PR isn't accepted, but it also might be a big hole.
2) Developing Panoptes to tolerate lowercase custom elements, and convert them to the mixed-case counterparts, which might involve some costly parsing of the feed content.
3) Developing Panoptes to interpret other sorts of valid elements as custom elements, and convert them, e.g. `<div component="DocTemplate" path="foo"></div>` becomes `<DocTemplate path="foo"/>`, which seems a little convoluted and would also require parsing the content
4) Mitigating the risk of Panoptes elements being stripped out, e.g. by forcing only the `Text` mode to be used, which negates many benefits of using a WYSIWYG CMS.
5) It feels like we've already crossed the Rubicon of trying to embed Panoptes elements in the CMS content, but maybe something like using `<iframe>`, instead, pointing to some kind of Panoptes-hosted document/template could bridge the two worlds.
