### ISSUE TITLE
Filter existing drugs lists by the `is_combination` column in pf_drugs

### ISSUE THREAD

**Issue by benjeffery** [wtchg-kwiatkowski/observatory-web#389]

**Comment by leehart** [comment]
I need to find where these appear.

**Comment by benjeffery** [comment]
I thought I put this in the QA column with a PR yesterday?

**Comment by leehart** [comment]
Yep, this is in the QA column. I'm trying to QA it.

**Comment by benjeffery** [comment]
Oh!
Anywhere it makes sense - drugs.html, site, region.

**Comment by leehart** [comment]
My sense of what makes sense is a problem here... I'm trying to make sense of it!

Why do the drug-combinations appear in some places and not others?

For example, they appear in the list of drugs/combos under "Drug resistance predictions in East southeast Asia" on
Home > Analysis  >  Resistance in P.f  >  Geographic Regions > East southeast Asia

But they don't appear on the site page, e.g. under "Predicted antimalarial drug resistance in Phuoc Long"
Home > Analysis  >  Resistance in P.f  >  Geographic Regions > East southeast Asia > Phuoc Long

I can't tell (yet) if this by design (sensical) or an error (nonsensical).

(I probably missed a convo last week.)

Why can't we show all combos everywhere we list drug resistance?
I understand it wouldn't make sense under a list of strictly "drugs" (not combos), but why not on that site page (for example).

Thanks in advance!

**Comment by benjeffery** [comment]
Sounds like I've made an omission! Let me check.

**Comment by benjeffery** [comment]
Ok that latest PR attached to this ticket should fix it.
